server:
  port: 8888

org:
  slf4j:
    simpleLogger:
      defaultLogLevel: debug

spring:
  datasource:
    url: jdbc:h2:mem:stocks
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

telegram:
  idChat: -759426700



